// This file automatically generated by:
//   Etch Version 0.95/java backend 0.95
//   Wed Aug 15 18:39:49 CDT 2007

package etch.examples.ccmuser;


/**
 */
public interface CcmUserServer extends CcmUser
{
	/**
	 */
	public void login(
		String serverIP
		, String username
		, String password
	)
	;
	/**
	 */
	public void logout(
	)
	;
	/**
	 */
	public etch.examples.ccmuser.CcmUser.UserConfiguration getUserConfig(
		String user
	)
	;
	/**
	 */
	public void setSpeeddialLabel(
		String pkid
		, String newLabel
	)
	;
	/**
	 */
	public void setSpeeddialNumber(
		String pkid
		, String newNumber
	)
	;
}
