// This file automatically generated by:
//   Etch Version 0.95/csharp backend 0.95
//   Wed Aug 15 18:39:49 CDT 2007

namespace etch.examples.ccmuser
{

using System;
using Etch.Msg;
using Etch.Support;
using Etch.Transport;



///
/// <summary>Call to message translator for CcmUser.</summary>
///
public class RemoteCcmUser : RemoteBase<ValueFactoryCcmUser>, CcmUser
{
	///
	/// <summary>Constructs the RemoteCcmUser.</summary>
	///
	/// <param name="svc"></param>
	///
	public RemoteCcmUser( DeliveryService svc ) : this( svc, new ValueFactoryCcmUser() )
	{
		
	}

	///
	/// <summary>Constructs the RemoteCcmUser.</summary>
	///
	/// <param name="svc"></param>
	/// <param name="vf"></param>
	///
	protected RemoteCcmUser( DeliveryService svc, ValueFactoryCcmUser vf ) : base( svc, vf )
	{
		
	}

}

}