// This file automatically generated by:
//   Etch Version 0.95/java backend 0.95
//   Wed Aug 15 18:39:49 CDT 2007

package etch.examples.ccmuser;


/**
 * Call to message translator for CcmUser.
 */
public class RemoteCcmUser extends etch.bindings.java.support.RemoteBase<ValueFactoryCcmUser> implements CcmUser
{
	/**
	 * Constructs the RemoteCcmUser.
	 *
	 * @param svc
	 */
	public RemoteCcmUser( etch.bindings.java.support.DeliveryService svc )
	{
		this( svc, new ValueFactoryCcmUser() );
	}

	/**
	 * Constructs the RemoteCcmUser.
	 *
	 * @param svc
	 * @param vf
	 */
	protected RemoteCcmUser( etch.bindings.java.support.DeliveryService svc, ValueFactoryCcmUser vf )
	{
		super( svc, vf );
	}

}
