// This file automatically generated by:
//   Etch Version 0.95/java backend 0.95
//   Wed Aug 15 18:39:49 CDT 2007

package etch.examples.ccmuser;


/**
 * Call to message translator for CcmUserServer.
 */
public class RemoteCcmUserServer extends RemoteCcmUser implements CcmUserServer
{
	/**
	 * Constructs the RemoteCcmUserServer.
	 *
	 * @param svc
	 */
	public RemoteCcmUserServer( etch.bindings.java.support.DeliveryService svc )
	{
		this( svc, new ValueFactoryCcmUser() );
	}

	/**
	 * Constructs the RemoteCcmUserServer.
	 *
	 * @param svc
	 * @param vf
	 */
	protected RemoteCcmUserServer( etch.bindings.java.support.DeliveryService svc, ValueFactoryCcmUser vf )
	{
		super( svc, vf );
	}

	public void login(
		String serverIP
		, String username
		, String password
	)
	{
		_end_login( _begin_login(
			serverIP
			, username
			, password
		) );
	}
	
	public etch.bindings.java.support.Mailbox<?> _begin_login(
		String serverIP
		, String username
		, String password
	)
	{
		etch.bindings.java.msg.Message _msg = _newMessage( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer_login );
		_msg.put( ValueFactoryCcmUser._mf_serverIP, serverIP );
		_msg.put( ValueFactoryCcmUser._mf_username, username );
		_msg.put( ValueFactoryCcmUser._mf_password, password );
		return _svc.begincall( _msg );
	}
	
	public void _end_login( etch.bindings.java.support.Mailbox<?> _mb )
	{
		try
		{
			
			_svc.endvoidcall( _mb,
				ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_login,
				ValueFactoryCcmUser._mf_result, 0 );
		}
		catch ( Exception _e )
		{
			if (_e instanceof RuntimeException) throw (RuntimeException) _e;
			throw new RuntimeException( "unexpected exception from peer", _e );
		}
	}

	public void logout(
	)
	{
		_end_logout( _begin_logout(
		) );
	}
	
	public etch.bindings.java.support.Mailbox<?> _begin_logout(
	)
	{
		etch.bindings.java.msg.Message _msg = _newMessage( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer_logout );
		return _svc.begincall( _msg );
	}
	
	public void _end_logout( etch.bindings.java.support.Mailbox<?> _mb )
	{
		try
		{
			
			_svc.endvoidcall( _mb,
				ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_logout,
				ValueFactoryCcmUser._mf_result, 0 );
		}
		catch ( Exception _e )
		{
			if (_e instanceof RuntimeException) throw (RuntimeException) _e;
			throw new RuntimeException( "unexpected exception from peer", _e );
		}
	}

	public etch.examples.ccmuser.CcmUser.UserConfiguration getUserConfig(
		String user
	)
	{
		return
		_end_getUserConfig( _begin_getUserConfig(
			user
		) );
	}
	
	public etch.bindings.java.support.Mailbox<?> _begin_getUserConfig(
		String user
	)
	{
		etch.bindings.java.msg.Message _msg = _newMessage( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer_getUserConfig );
		_msg.put( ValueFactoryCcmUser._mf_user, user );
		return _svc.begincall( _msg );
	}
	
	public etch.examples.ccmuser.CcmUser.UserConfiguration _end_getUserConfig( etch.bindings.java.support.Mailbox<?> _mb )
	{
		try
		{
			return
				(etch.examples.ccmuser.CcmUser.UserConfiguration)
					_svc.endcall( _mb,
						ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_getUserConfig,
						ValueFactoryCcmUser._mf_result, 0 )
				;
		}
		catch ( Exception _e )
		{
			if (_e instanceof RuntimeException) throw (RuntimeException) _e;
			throw new RuntimeException( "unexpected exception from peer", _e );
		}
	}

	public void setSpeeddialLabel(
		String pkid
		, String newLabel
	)
	{
		_end_setSpeeddialLabel( _begin_setSpeeddialLabel(
			pkid
			, newLabel
		) );
	}
	
	public etch.bindings.java.support.Mailbox<?> _begin_setSpeeddialLabel(
		String pkid
		, String newLabel
	)
	{
		etch.bindings.java.msg.Message _msg = _newMessage( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer_setSpeeddialLabel );
		_msg.put( ValueFactoryCcmUser._mf_pkid, pkid );
		_msg.put( ValueFactoryCcmUser._mf_newLabel, newLabel );
		return _svc.begincall( _msg );
	}
	
	public void _end_setSpeeddialLabel( etch.bindings.java.support.Mailbox<?> _mb )
	{
		try
		{
			
			_svc.endvoidcall( _mb,
				ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialLabel,
				ValueFactoryCcmUser._mf_result, 0 );
		}
		catch ( Exception _e )
		{
			if (_e instanceof RuntimeException) throw (RuntimeException) _e;
			throw new RuntimeException( "unexpected exception from peer", _e );
		}
	}

	public void setSpeeddialNumber(
		String pkid
		, String newNumber
	)
	{
		_end_setSpeeddialNumber( _begin_setSpeeddialNumber(
			pkid
			, newNumber
		) );
	}
	
	public etch.bindings.java.support.Mailbox<?> _begin_setSpeeddialNumber(
		String pkid
		, String newNumber
	)
	{
		etch.bindings.java.msg.Message _msg = _newMessage( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer_setSpeeddialNumber );
		_msg.put( ValueFactoryCcmUser._mf_pkid, pkid );
		_msg.put( ValueFactoryCcmUser._mf_newNumber, newNumber );
		return _svc.begincall( _msg );
	}
	
	public void _end_setSpeeddialNumber( etch.bindings.java.support.Mailbox<?> _mb )
	{
		try
		{
			
			_svc.endvoidcall( _mb,
				ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialNumber,
				ValueFactoryCcmUser._mf_result, 0 );
		}
		catch ( Exception _e )
		{
			if (_e instanceof RuntimeException) throw (RuntimeException) _e;
			throw new RuntimeException( "unexpected exception from peer", _e );
		}
	}

}
