// This file automatically generated by:
//   Etch Version 0.95/csharp backend 0.95
//   Wed Aug 15 18:39:49 CDT 2007

namespace etch.examples.ccmuser
{

using System;
using Etch.Msg;
using Etch.Support;
using Etch.Transport;


///
/// <summary>Call to message translator for CcmUserClient.</summary>
///
public class RemoteCcmUserClient : RemoteCcmUser, CcmUserClient
{
	///
	/// <summary>Constructs the RemoteCcmUserClient.</summary>
	///
	/// <param name="svc"></param>
	///
	public RemoteCcmUserClient( DeliveryService svc ) : this( svc, new ValueFactoryCcmUser() )
	{
		
	}

	///
	/// <summary>Constructs the RemoteCcmUserClient.</summary>
	///
	/// <param name="svc"></param>
	/// <param name="vf"></param>
	///
	protected RemoteCcmUserClient( DeliveryService svc, ValueFactoryCcmUser vf ) : base( svc, vf )
	{
		
	}

	public void DoINeedThis(
	)
	{
		_end_DoINeedThis( _begin_DoINeedThis(
		) );
	}
	
	public Mailbox<MailboxMessageSource> _begin_DoINeedThis(
	)
	{
		Message _msg = _NewMessage( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserClient_DoINeedThis );
		return _svc.BeginCall( _msg );
	}
	
	public void _end_DoINeedThis( Mailbox<MailboxMessageSource> _mb )
	{
		try
		{
			
			_svc.EndVoidCall( _mb,
				ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_DoINeedThis,
				ValueFactoryCcmUser._mf_result, 0 );
		}
		catch ( Exception _e )
		{
			throw new Exception( "unexpected", _e );
		}
	}

}

}