# This file automatically generated by:
#   Etch Version 0.95/ruby backend 0.95
#   Wed Aug 15 18:39:49 CDT 2007

require 'etch/bindings/ruby/msg/message'
require 'etch/bindings/ruby/support/delivery_service'
require 'etch/bindings/ruby/support/mailbox'
require 'etch/bindings/ruby/idl/test/Test'

require 'etch/bindings/ruby/support/remote_base'

#
# Call to message translator for CcmUser.
#
class RemoteCcmUser < RemoteBase 
	include CcmUser

	#
	# Constructs the RemoteCcmUser.
	#
	# @param svc
	#
	# first param should be delivery service
	# second param should be the value factory (optional)
	def initialize( *args )
		
		if ( args[1] == nil)
			super( args[0], ValueFactoryCcmUser.new )
		else
			super( args[0], args[1] )
		end	
	end

end
