// This file automatically generated by:
//   Etch Version 0.95/java backend 0.95
//   Wed Aug 15 18:39:49 CDT 2007

package etch.examples.ccmuser;


/**
 * Call to message translator for CcmUserClient.
 */
public class RemoteCcmUserClient extends RemoteCcmUser implements CcmUserClient
{
	/**
	 * Constructs the RemoteCcmUserClient.
	 *
	 * @param svc
	 */
	public RemoteCcmUserClient( etch.bindings.java.support.DeliveryService svc )
	{
		this( svc, new ValueFactoryCcmUser() );
	}

	/**
	 * Constructs the RemoteCcmUserClient.
	 *
	 * @param svc
	 * @param vf
	 */
	protected RemoteCcmUserClient( etch.bindings.java.support.DeliveryService svc, ValueFactoryCcmUser vf )
	{
		super( svc, vf );
	}

	public void DoINeedThis(
	)
	{
		_end_DoINeedThis( _begin_DoINeedThis(
		) );
	}
	
	public etch.bindings.java.support.Mailbox<?> _begin_DoINeedThis(
	)
	{
		etch.bindings.java.msg.Message _msg = _newMessage( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserClient_DoINeedThis );
		return _svc.begincall( _msg );
	}
	
	public void _end_DoINeedThis( etch.bindings.java.support.Mailbox<?> _mb )
	{
		try
		{
			
			_svc.endvoidcall( _mb,
				ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_DoINeedThis,
				ValueFactoryCcmUser._mf_result, 0 );
		}
		catch ( Exception _e )
		{
			if (_e instanceof RuntimeException) throw (RuntimeException) _e;
			throw new RuntimeException( "unexpected exception from peer", _e );
		}
	}

}
