# This file automatically generated by:
#   Etch Version 0.95/ruby backend 0.95
#   Wed Aug 15 18:39:49 CDT 2007

# package etch.compiler.ast.Service@765291/parent()/name();

require 'etch/bindings/ruby/msg/message'
require 'etch/bindings/ruby/support/message_source'
require 'etch/bindings/ruby/support/pool'
require 'etch/bindings/ruby/support/etch__auth_exception'
require 'etch/bindings/ruby/support/who'
require 'etch/bindings/ruby/support/default_value_factory'
require 'etch/bindings/ruby/idl/test/ValueFactoryTest'
require 'etch/bindings/ruby/idl/test/StubCcmUser'

# import etch.bindings.java.support.Pool.PoolRunnable;

# 
# Message to call translator for CcmUserServer.
# 
class StubCcmUserServer < StubCcmUser

	#
	# Stub for CcmUserServer.
	# @param obj the implementation of CcmUserServer responsive to requests.
	# @param pool thread pool used to run AsyncReceiverMode.FREE methods.
	# @param free thread pool used to run AsyncReceiverMode.FREE methods.
	#
	def initialize( obj, pool, free )
	
		super( obj, pool, free )
		@_obj = obj
		@vf = ValueFactoryCcmUser.new
	end
	
	def message( _src, _sender, _msg )
	
		if (_msg == nil)
		
			super.message( _src, _sender, _msg )
			return true
		end

		case (_msg.getType().xid)
			when nil then raise "nil id"
			when -267962576 then begin
				do_login( _src, _sender, _msg )
				return true
			end
			when 1274147843 then begin
				do_logout( _src, _sender, _msg )
				return true
			end
			when 1580300234 then begin
				do_getUserConfig( _src, _sender, _msg )
				return true
			end
			when -1839976634 then begin
				do_setSpeeddialLabel( _src, _sender, _msg )
				return true
			end
			when -1424516809 then begin
				do_setSpeeddialNumber( _src, _sender, _msg )
				return true
			end
			
			else return super.message( _src, _sender, _msg )
		end
	end

	#
	# @param _src
	# @param _sender
	# @param _msg
	#
	def do_login( _src, _sender, _msg )
	
		begin
		
			serverIP =
					_msg[ ValueFactoryCcmUser::MF_serverIP ]
			username =
					_msg[ ValueFactoryCcmUser::MF_username ]
			password =
					_msg[ ValueFactoryCcmUser::MF_password ]

			@_obj.login(serverIP, username, password	)

			_rmsg = _msg.reply( ValueFactoryCcmUser::MT_etch_examples_ccmuser_CcmUserServer__result_login )
			_src.message( _sender, _rmsg )
		
		rescue Exception => e 
		
			_rmsg = _msg.reply( ValueFactoryCcmUser::MT_etch_examples_ccmuser_CcmUserServer__result_login )
			_rmsg.store( ValueFactoryCcmUser::MF_result, e )
			_src.message( _sender, _rmsg )
		end
	end

	#
	# @param _src
	# @param _sender
	# @param _msg
	#
	def do_logout( _src, _sender, _msg )
	
		begin
		

			@_obj.logout(	)

			_rmsg = _msg.reply( ValueFactoryCcmUser::MT_etch_examples_ccmuser_CcmUserServer__result_logout )
			_src.message( _sender, _rmsg )
		
		rescue Exception => e 
		
			_rmsg = _msg.reply( ValueFactoryCcmUser::MT_etch_examples_ccmuser_CcmUserServer__result_logout )
			_rmsg.store( ValueFactoryCcmUser::MF_result, e )
			_src.message( _sender, _rmsg )
		end
	end

	#
	# @param _src
	# @param _sender
	# @param _msg
	#
	def do_getUserConfig( _src, _sender, _msg )
	
		begin
		
			user =
					_msg[ ValueFactoryCcmUser::MF_user ]

			_result =
			@_obj.getUserConfig(user	)

			_rmsg = _msg.reply( ValueFactoryCcmUser::MT_etch_examples_ccmuser_CcmUserServer__result_getUserConfig )
			_rmsg.store( ValueFactoryCcmUser::MF_result, _result )
			_src.message( _sender, _rmsg )
		
		rescue Exception => e 
		
			_rmsg = _msg.reply( ValueFactoryCcmUser::MT_etch_examples_ccmuser_CcmUserServer__result_getUserConfig )
			_rmsg.store( ValueFactoryCcmUser::MF_result, e )
			_src.message( _sender, _rmsg )
		end
	end

	#
	# @param _src
	# @param _sender
	# @param _msg
	#
	def do_setSpeeddialLabel( _src, _sender, _msg )
	
		begin
		
			pkid =
					_msg[ ValueFactoryCcmUser::MF_pkid ]
			newLabel =
					_msg[ ValueFactoryCcmUser::MF_newLabel ]

			@_obj.setSpeeddialLabel(pkid, newLabel	)

			_rmsg = _msg.reply( ValueFactoryCcmUser::MT_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialLabel )
			_src.message( _sender, _rmsg )
		
		rescue Exception => e 
		
			_rmsg = _msg.reply( ValueFactoryCcmUser::MT_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialLabel )
			_rmsg.store( ValueFactoryCcmUser::MF_result, e )
			_src.message( _sender, _rmsg )
		end
	end

	#
	# @param _src
	# @param _sender
	# @param _msg
	#
	def do_setSpeeddialNumber( _src, _sender, _msg )
	
		begin
		
			pkid =
					_msg[ ValueFactoryCcmUser::MF_pkid ]
			newNumber =
					_msg[ ValueFactoryCcmUser::MF_newNumber ]

			@_obj.setSpeeddialNumber(pkid, newNumber	)

			_rmsg = _msg.reply( ValueFactoryCcmUser::MT_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialNumber )
			_src.message( _sender, _rmsg )
		
		rescue Exception => e 
		
			_rmsg = _msg.reply( ValueFactoryCcmUser::MT_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialNumber )
			_rmsg.store( ValueFactoryCcmUser::MF_result, e )
			_src.message( _sender, _rmsg )
		end
	end
end