// This file automatically generated by:
//   Etch Version 0.95/java backend 0.95
//   Wed Aug 15 18:39:49 CDT 2007

package etch.examples.ccmuser;

import etch.bindings.java.msg.Message;
import etch.bindings.java.support.MessageSource;
import etch.bindings.java.support.Pool;
import etch.bindings.java.support._Etch_AuthException;
import metreos.core.Who;
import etch.bindings.java.support.Pool.PoolRunnable;

/**
 * Message to call translator for CcmUserServer.
 */
public class StubCcmUserServer extends StubCcmUser
{
	/**
	 * Stub for CcmUserServer.
	 * @param obj the implementation of CcmUserServer responsive to requests.
	 * @param pool thread pool used to run AsyncReceiverMode.FREE methods.
	 * @param free thread pool used to run AsyncReceiverMode.FREE methods.
	 */
	public StubCcmUserServer( CcmUserServer obj, Pool pool, Pool free )
	{
		super( obj, pool, free );
		this._obj = obj;
	}
	
	@SuppressWarnings("unused")
	private final CcmUserServer _obj;

	@Override
	public boolean message( final MessageSource _src, final Who _sender, final Message _msg )
		throws Exception
	{
		if (_msg == null)
		{
			super.message( _src, _sender, _msg );
			return true;
		}

		switch (_msg.type().getId())
		{
			case -267962576: // ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer_login
				do_login( _src, _sender, _msg );
				return true;
			case 1274147843: // ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer_logout
				do_logout( _src, _sender, _msg );
				return true;
			case 1580300234: // ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer_getUserConfig
				do_getUserConfig( _src, _sender, _msg );
				return true;
			case -1839976634: // ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer_setSpeeddialLabel
				do_setSpeeddialLabel( _src, _sender, _msg );
				return true;
			case -1424516809: // ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer_setSpeeddialNumber
				do_setSpeeddialNumber( _src, _sender, _msg );
				return true;
			default:
				return super.message( _src, _sender, _msg );
		}
	}

	/**
	 * @param _src
	 * @param _sender
	 * @param _msg
	 * @throws Exception
	 */
	final void do_login( final MessageSource _src, final Who _sender, final Message _msg )
		throws Exception
	{
		try
		{
			String serverIP =
				(String)
					_msg.get( ValueFactoryCcmUser._mf_serverIP )
				;
			String username =
				(String)
					_msg.get( ValueFactoryCcmUser._mf_username )
				;
			String password =
				(String)
					_msg.get( ValueFactoryCcmUser._mf_password )
				;

			_obj.login(
				serverIP
				, username
				, password
			);

			Message _rmsg = _msg.reply( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_login );
			_src.message( _sender, _rmsg );
		}
		catch ( Exception e )
		{
			Message _rmsg = _msg.reply( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_login );
			_rmsg.put( ValueFactoryCcmUser._mf_result, e );
			_src.message( _sender, _rmsg );
		}
	}

	/**
	 * @param _src
	 * @param _sender
	 * @param _msg
	 * @throws Exception
	 */
	final void do_logout( final MessageSource _src, final Who _sender, final Message _msg )
		throws Exception
	{
		try
		{

			_obj.logout(
			);

			Message _rmsg = _msg.reply( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_logout );
			_src.message( _sender, _rmsg );
		}
		catch ( Exception e )
		{
			Message _rmsg = _msg.reply( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_logout );
			_rmsg.put( ValueFactoryCcmUser._mf_result, e );
			_src.message( _sender, _rmsg );
		}
	}

	/**
	 * @param _src
	 * @param _sender
	 * @param _msg
	 * @throws Exception
	 */
	final void do_getUserConfig( final MessageSource _src, final Who _sender, final Message _msg )
		throws Exception
	{
		try
		{
			String user =
				(String)
					_msg.get( ValueFactoryCcmUser._mf_user )
				;

			Object _result =
			_obj.getUserConfig(
				user
			);

			Message _rmsg = _msg.reply( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_getUserConfig );
			_rmsg.put( ValueFactoryCcmUser._mf_result, _result );
			_src.message( _sender, _rmsg );
		}
		catch ( Exception e )
		{
			Message _rmsg = _msg.reply( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_getUserConfig );
			_rmsg.put( ValueFactoryCcmUser._mf_result, e );
			_src.message( _sender, _rmsg );
		}
	}

	/**
	 * @param _src
	 * @param _sender
	 * @param _msg
	 * @throws Exception
	 */
	final void do_setSpeeddialLabel( final MessageSource _src, final Who _sender, final Message _msg )
		throws Exception
	{
		try
		{
			String pkid =
				(String)
					_msg.get( ValueFactoryCcmUser._mf_pkid )
				;
			String newLabel =
				(String)
					_msg.get( ValueFactoryCcmUser._mf_newLabel )
				;

			_obj.setSpeeddialLabel(
				pkid
				, newLabel
			);

			Message _rmsg = _msg.reply( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialLabel );
			_src.message( _sender, _rmsg );
		}
		catch ( Exception e )
		{
			Message _rmsg = _msg.reply( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialLabel );
			_rmsg.put( ValueFactoryCcmUser._mf_result, e );
			_src.message( _sender, _rmsg );
		}
	}

	/**
	 * @param _src
	 * @param _sender
	 * @param _msg
	 * @throws Exception
	 */
	final void do_setSpeeddialNumber( final MessageSource _src, final Who _sender, final Message _msg )
		throws Exception
	{
		try
		{
			String pkid =
				(String)
					_msg.get( ValueFactoryCcmUser._mf_pkid )
				;
			String newNumber =
				(String)
					_msg.get( ValueFactoryCcmUser._mf_newNumber )
				;

			_obj.setSpeeddialNumber(
				pkid
				, newNumber
			);

			Message _rmsg = _msg.reply( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialNumber );
			_src.message( _sender, _rmsg );
		}
		catch ( Exception e )
		{
			Message _rmsg = _msg.reply( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialNumber );
			_rmsg.put( ValueFactoryCcmUser._mf_result, e );
			_src.message( _sender, _rmsg );
		}
	}
}
