# This file automatically generated by:
#   Etch Version 0.95/ruby backend 0.95
#   Wed Aug 15 18:39:49 CDT 2007

# package etch.compiler.ast.Service@765291/parent()/name();

require 'etch/bindings/ruby/msg/message'
require 'etch/bindings/ruby/support/message_source'
require 'etch/bindings/ruby/support/pool'
require 'etch/bindings/ruby/support/etch__auth_exception'
require 'etch/bindings/ruby/support/who'
require 'etch/bindings/ruby/support/default_value_factory'
require 'etch/bindings/ruby/idl/test/ValueFactoryTest'
require 'etch/bindings/ruby/idl/test/StubCcmUser'

# import etch.bindings.java.support.Pool.PoolRunnable;

# 
# Message to call translator for CcmUserClient.
# 
class StubCcmUserClient < StubCcmUser

	#
	# Stub for CcmUserClient.
	# @param obj the implementation of CcmUserClient responsive to requests.
	# @param pool thread pool used to run AsyncReceiverMode.FREE methods.
	# @param free thread pool used to run AsyncReceiverMode.FREE methods.
	#
	def initialize( obj, pool, free )
	
		super( obj, pool, free )
		@_obj = obj
		@vf = ValueFactoryCcmUser.new
	end
	
	def message( _src, _sender, _msg )
	
		if (_msg == nil)
		
			super.message( _src, _sender, _msg )
			return true
		end

		case (_msg.getType().xid)
			when nil then raise "nil id"
			when -557621791 then begin
				do_DoINeedThis( _src, _sender, _msg )
				return true
			end
			
			else return super.message( _src, _sender, _msg )
		end
	end

	#
	# @param _src
	# @param _sender
	# @param _msg
	#
	def do_DoINeedThis( _src, _sender, _msg )
	
		begin
		

			@_obj.DoINeedThis(	)

			_rmsg = _msg.reply( ValueFactoryCcmUser::MT_etch_examples_ccmuser_CcmUserServer__result_DoINeedThis )
			_src.message( _sender, _rmsg )
		
		rescue Exception => e 
		
			_rmsg = _msg.reply( ValueFactoryCcmUser::MT_etch_examples_ccmuser_CcmUserServer__result_DoINeedThis )
			_rmsg.store( ValueFactoryCcmUser::MF_result, e )
			_src.message( _sender, _rmsg )
		end
	end
end