// This file automatically generated by:
//   Etch Version 0.95/csharp backend 0.95
//   Wed Aug 15 18:39:49 CDT 2007

namespace etch.examples.ccmuser
{


using System;
using Etch.Msg;
using Etch.Transport;
using Etch.Support;


///
///<summary> Message to call translator for CcmUserClient. </summary>
///
public class StubCcmUserClient : StubCcmUser
{
	///
	/// <summary>Stub for CcmUserClient.</summary>
	/// <param name="obj"> the implementation of CcmUserClient responsive to requests.</param>
	/// <param name="pool"> thread pool used to run AsyncReceiverMode.POOL methods.</param>
	/// <param name="free"> thread pool used to run AsyncReceiverMode.FREE methods..</param>
	///
	public StubCcmUserClient( CcmUserClient obj, Pool pool, Pool free ) : base( obj, pool, free )
	{	
		this._obj = obj;
	}
	
	private CcmUserClient _obj;

	public override bool Message( MessageSource _src, Who _sender, Message _msg ) 
	{
		if (_msg == null)
		{
			base.Message( _src, _sender, _msg );
			return true;
		}

		switch (_msg.GetXType.Id)
		{
			case -557621791: // ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserClient_DoINeedThis
				do_DoINeedThis( _src, _sender, _msg );
				return true;
			default:
				return base.Message( _src, _sender, _msg );
		}
	}

	///
	/// <param name="_src"></param>
	/// <param name="_sender"></param>
	/// <param name="_msg"></param>
	/// Exception:
	///		throws Exception	
	///
	void do_DoINeedThis( MessageSource _src, Who _sender, Message _msg )
	{
		try
		{

			_obj.DoINeedThis(
			);

			Message _rmsg = _msg.Reply( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_DoINeedThis );
			_src.Message( _sender, _rmsg );
		}
		catch ( Exception e )
		{
			Message _rmsg = _msg.Reply( ValueFactoryCcmUser._mt_etch_examples_ccmuser_CcmUserServer__result_DoINeedThis );
			_rmsg.Add( ValueFactoryCcmUser._mf_result, e );
			_src.Message( _sender, _rmsg );
		}
	}
}

}