// This file automatically generated by:
//   Etch Version 0.95/java backend 0.95
//   Wed Aug 15 18:39:49 CDT 2007

package etch.examples.ccmuser;

import etch.bindings.java.msg.Field;
import etch.bindings.java.msg.Type;
import etch.bindings.java.msg.StructValue;
import etch.bindings.java.support.DefaultValueFactory;

/**
 * ValueFactory for CcmUser.
 */
public class ValueFactoryCcmUser extends DefaultValueFactory
{
	/**
	 * Construct the ValueFactoryCcmUser.
	 */
	public ValueFactoryCcmUser()
	{
	}

	/** Type for etch.examples.ccmuser.CcmUser.UserConfiguration */
	public static final Type _mt_etch_examples_ccmuser_CcmUser_UserConfiguration = new Type( 584321839, "etch.examples.ccmuser.CcmUser.UserConfiguration" );
	// { addType( _mt_etch_examples_ccmuser_CcmUser_UserConfiguration ); }

	/** Type for etch.examples.ccmuser.CcmUser.Device */
	public static final Type _mt_etch_examples_ccmuser_CcmUser_Device = new Type( 1396020274, "etch.examples.ccmuser.CcmUser.Device" );
	// { addType( _mt_etch_examples_ccmuser_CcmUser_Device ); }

	/** Type for etch.examples.ccmuser.CcmUser.Speeddial */
	public static final Type _mt_etch_examples_ccmuser_CcmUser_Speeddial = new Type( 1136827771, "etch.examples.ccmuser.CcmUser.Speeddial" );
	// { addType( _mt_etch_examples_ccmuser_CcmUser_Speeddial ); }

	/** Type for etch.examples.ccmuser.CcmUserServer.login */
	public static final Type _mt_etch_examples_ccmuser_CcmUserServer_login = new Type( -267962576, "etch.examples.ccmuser.CcmUserServer.login" );
	// { addType( _mt_etch_examples_ccmuser_CcmUserServer_login ); }

	/** Type for etch.examples.ccmuser.CcmUserServer._result_login */
	public static final Type _mt_etch_examples_ccmuser_CcmUserServer__result_login = new Type( 28137389, "etch.examples.ccmuser.CcmUserServer._result_login" );
	// { addType( _mt_etch_examples_ccmuser_CcmUserServer__result_login ); }

	/** Type for etch.examples.ccmuser.CcmUserServer.logout */
	public static final Type _mt_etch_examples_ccmuser_CcmUserServer_logout = new Type( 1274147843, "etch.examples.ccmuser.CcmUserServer.logout" );
	// { addType( _mt_etch_examples_ccmuser_CcmUserServer_logout ); }

	/** Type for etch.examples.ccmuser.CcmUserServer._result_logout */
	public static final Type _mt_etch_examples_ccmuser_CcmUserServer__result_logout = new Type( -1001327930, "etch.examples.ccmuser.CcmUserServer._result_logout" );
	// { addType( _mt_etch_examples_ccmuser_CcmUserServer__result_logout ); }

	/** Type for etch.examples.ccmuser.CcmUserServer.getUserConfig */
	public static final Type _mt_etch_examples_ccmuser_CcmUserServer_getUserConfig = new Type( 1580300234, "etch.examples.ccmuser.CcmUserServer.getUserConfig" );
	// { addType( _mt_etch_examples_ccmuser_CcmUserServer_getUserConfig ); }

	/** Type for etch.examples.ccmuser.CcmUserServer._result_getUserConfig */
	public static final Type _mt_etch_examples_ccmuser_CcmUserServer__result_getUserConfig = new Type( -282501561, "etch.examples.ccmuser.CcmUserServer._result_getUserConfig" );
	// { addType( _mt_etch_examples_ccmuser_CcmUserServer__result_getUserConfig ); }

	/** Type for etch.examples.ccmuser.CcmUserServer.setSpeeddialLabel */
	public static final Type _mt_etch_examples_ccmuser_CcmUserServer_setSpeeddialLabel = new Type( -1839976634, "etch.examples.ccmuser.CcmUserServer.setSpeeddialLabel" );
	// { addType( _mt_etch_examples_ccmuser_CcmUserServer_setSpeeddialLabel ); }

	/** Type for etch.examples.ccmuser.CcmUserServer._result_setSpeeddialLabel */
	public static final Type _mt_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialLabel = new Type( 1410365635, "etch.examples.ccmuser.CcmUserServer._result_setSpeeddialLabel" );
	// { addType( _mt_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialLabel ); }

	/** Type for etch.examples.ccmuser.CcmUserServer.setSpeeddialNumber */
	public static final Type _mt_etch_examples_ccmuser_CcmUserServer_setSpeeddialNumber = new Type( -1424516809, "etch.examples.ccmuser.CcmUserServer.setSpeeddialNumber" );
	// { addType( _mt_etch_examples_ccmuser_CcmUserServer_setSpeeddialNumber ); }

	/** Type for etch.examples.ccmuser.CcmUserServer._result_setSpeeddialNumber */
	public static final Type _mt_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialNumber = new Type( -1578455302, "etch.examples.ccmuser.CcmUserServer._result_setSpeeddialNumber" );
	// { addType( _mt_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialNumber ); }

	/** Type for etch.examples.ccmuser.CcmUserClient.DoINeedThis */
	public static final Type _mt_etch_examples_ccmuser_CcmUserClient_DoINeedThis = new Type( -557621791, "etch.examples.ccmuser.CcmUserClient.DoINeedThis" );
	// { addType( _mt_etch_examples_ccmuser_CcmUserClient_DoINeedThis ); }

	/** Type for etch.examples.ccmuser.CcmUserServer._result_DoINeedThis */
	public static final Type _mt_etch_examples_ccmuser_CcmUserServer__result_DoINeedThis = new Type( 1085071830, "etch.examples.ccmuser.CcmUserServer._result_DoINeedThis" );
	// { addType( _mt_etch_examples_ccmuser_CcmUserServer__result_DoINeedThis ); }

	@Override
	public Type getType( Integer id )
	{
		switch (id)
		{
			case 584321839: return _mt_etch_examples_ccmuser_CcmUser_UserConfiguration;
			case 1396020274: return _mt_etch_examples_ccmuser_CcmUser_Device;
			case 1136827771: return _mt_etch_examples_ccmuser_CcmUser_Speeddial;
			case -267962576: return _mt_etch_examples_ccmuser_CcmUserServer_login;
			case 28137389: return _mt_etch_examples_ccmuser_CcmUserServer__result_login;
			case 1274147843: return _mt_etch_examples_ccmuser_CcmUserServer_logout;
			case -1001327930: return _mt_etch_examples_ccmuser_CcmUserServer__result_logout;
			case 1580300234: return _mt_etch_examples_ccmuser_CcmUserServer_getUserConfig;
			case -282501561: return _mt_etch_examples_ccmuser_CcmUserServer__result_getUserConfig;
			case -1839976634: return _mt_etch_examples_ccmuser_CcmUserServer_setSpeeddialLabel;
			case 1410365635: return _mt_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialLabel;
			case -1424516809: return _mt_etch_examples_ccmuser_CcmUserServer_setSpeeddialNumber;
			case -1578455302: return _mt_etch_examples_ccmuser_CcmUserServer__result_setSpeeddialNumber;
			case -557621791: return _mt_etch_examples_ccmuser_CcmUserClient_DoINeedThis;
			case 1085071830: return _mt_etch_examples_ccmuser_CcmUserServer__result_DoINeedThis;
			default: return super.getType( id );
		}
	}

	@Override
	public StructValue exportCustomValue( Object value )
	{
		Class<?> clss = value.getClass();

		if (clss == etch.examples.ccmuser.CcmUser.UserConfiguration.class)
		{
			StructValue struct = new StructValue( _mt_etch_examples_ccmuser_CcmUser_UserConfiguration );
			etch.examples.ccmuser.CcmUser.UserConfiguration v = (etch.examples.ccmuser.CcmUser.UserConfiguration) value;
			struct.put( _mf_devices, v.devices );
			return struct;
		}

		if (clss == etch.examples.ccmuser.CcmUser.Device.class)
		{
			StructValue struct = new StructValue( _mt_etch_examples_ccmuser_CcmUser_Device );
			etch.examples.ccmuser.CcmUser.Device v = (etch.examples.ccmuser.CcmUser.Device) value;
			struct.put( _mf_name, v.name );
			struct.put( _mf_description, v.description );
			struct.put( _mf_type, v.type );
			struct.put( _mf_speeddials, v.speeddials );
			return struct;
		}

		if (clss == etch.examples.ccmuser.CcmUser.Speeddial.class)
		{
			StructValue struct = new StructValue( _mt_etch_examples_ccmuser_CcmUser_Speeddial );
			etch.examples.ccmuser.CcmUser.Speeddial v = (etch.examples.ccmuser.CcmUser.Speeddial) value;
			struct.put( _mf_pkid, v.pkid );
			struct.put( _mf_number, v.number );
			struct.put( _mf_label, v.label );
			return struct;
		}

		return super.exportCustomValue( value );
	}

	@Override
	public Object importCustomValue( StructValue struct )
	{
		Type type = struct.type();
		switch( type.getId() )
		{
			case 584321839 /* struct/except _mt_etch_examples_ccmuser_CcmUser_UserConfiguration */:
			{
				return new etch.examples.ccmuser.CcmUser.UserConfiguration(
					(etch.examples.ccmuser.CcmUser.Device[])
//					to_Device(
//						etch.examples.ccmuser.CcmUser.Device[].class,
						struct.get( _mf_devices )
//					)
				);
			}

			case 1396020274 /* struct/except _mt_etch_examples_ccmuser_CcmUser_Device */:
			{
				return new etch.examples.ccmuser.CcmUser.Device(
					(String)
						struct.get( _mf_name )
					, (String)
						struct.get( _mf_description )
					, (String)
						struct.get( _mf_type )
					, (etch.examples.ccmuser.CcmUser.Speeddial[])
//					to_Speeddial(
//						etch.examples.ccmuser.CcmUser.Speeddial[].class,
						struct.get( _mf_speeddials )
//					)
				);
			}

			case 1136827771 /* struct/except _mt_etch_examples_ccmuser_CcmUser_Speeddial */:
			{
				return new etch.examples.ccmuser.CcmUser.Speeddial(
					(String)
						struct.get( _mf_pkid )
					, (String)
						struct.get( _mf_number )
					, (String)
						struct.get( _mf_label )
				);
			}

		}
		return super.importCustomValue( struct );
	}

	@Override
	public Type getCustomStructType( Class<?> c )
	{
		//if (c == Date.class) return _mt__Etch_Date;
		if (c == etch.examples.ccmuser.CcmUser.UserConfiguration.class) return _mt_etch_examples_ccmuser_CcmUser_UserConfiguration;
		if (c == etch.examples.ccmuser.CcmUser.Device.class) return _mt_etch_examples_ccmuser_CcmUser_Device;
		if (c == etch.examples.ccmuser.CcmUser.Speeddial.class) return _mt_etch_examples_ccmuser_CcmUser_Speeddial;
		return null;
	}

	@Override
	public Class<?> getCustomType( Type type )
	{
		switch (type.getId())
		{
//			case -1201742561 /* _mt__Etch_Date */: return Date.class;
			case 584321839 /* _mt_etch_examples_ccmuser_CcmUser_UserConfiguration */: return etch.examples.ccmuser.CcmUser.UserConfiguration.class;
			case 1396020274 /* _mt_etch_examples_ccmuser_CcmUser_Device */: return etch.examples.ccmuser.CcmUser.Device.class;
			case 1136827771 /* _mt_etch_examples_ccmuser_CcmUser_Speeddial */: return etch.examples.ccmuser.CcmUser.Speeddial.class;
		}
		
		return null;
	}

	/** Field for devices */
	public static final Field _mf_devices = new Field( -1600574216, "devices" );
	//{ addField( _mf_devices ); }
	
	/** Field for name */
	public static final Field _mf_name = new Field( -444097232, "name" );
	//{ addField( _mf_name ); }
	
	/** Field for description */
	public static final Field _mf_description = new Field( -337887177, "description" );
	//{ addField( _mf_description ); }
	
	/** Field for type */
	public static final Field _mf_type = new Field( 142931583, "type" );
	//{ addField( _mf_type ); }
	
	/** Field for speeddials */
	public static final Field _mf_speeddials = new Field( -618273087, "speeddials" );
	//{ addField( _mf_speeddials ); }
	
	/** Field for pkid */
	public static final Field _mf_pkid = new Field( 1199429819, "pkid" );
	//{ addField( _mf_pkid ); }
	
	/** Field for number */
	public static final Field _mf_number = new Field( 1183734798, "number" );
	//{ addField( _mf_number ); }
	
	/** Field for label */
	public static final Field _mf_label = new Field( -1941158225, "label" );
	//{ addField( _mf_label ); }
	
	/** Field for serverIP */
	public static final Field _mf_serverIP = new Field( -1102239153, "serverIP" );
	//{ addField( _mf_serverIP ); }
	
	/** Field for username */
	public static final Field _mf_username = new Field( 626623675, "username" );
	//{ addField( _mf_username ); }
	
	/** Field for password */
	public static final Field _mf_password = new Field( 184363104, "password" );
	//{ addField( _mf_password ); }
	
	/** Field for result */
	public static final Field _mf_result = new Field( -2130379326, "result" );
	//{ addField( _mf_result ); }
	
	/** Field for user */
	public static final Field _mf_user = new Field( 873228176, "user" );
	//{ addField( _mf_user ); }
	
	/** Field for newLabel */
	public static final Field _mf_newLabel = new Field( 388681113, "newLabel" );
	//{ addField( _mf_newLabel ); }
	
	/** Field for newNumber */
	public static final Field _mf_newNumber = new Field( -96759900, "newNumber" );
	//{ addField( _mf_newNumber ); }
	
	@Override
	public Field getField( Integer id )
	{
		switch (id)
		{
			case -1600574216: return _mf_devices;
			case -444097232: return _mf_name;
			case -337887177: return _mf_description;
			case 142931583: return _mf_type;
			case -618273087: return _mf_speeddials;
			case 1199429819: return _mf_pkid;
			case 1183734798: return _mf_number;
			case -1941158225: return _mf_label;
			case -1102239153: return _mf_serverIP;
			case 626623675: return _mf_username;
			case 184363104: return _mf_password;
			case -2130379326: return _mf_result;
			case 873228176: return _mf_user;
			case 388681113: return _mf_newLabel;
			case -96759900: return _mf_newNumber;
			default: return super.getField( id );
		}
	}
//
//	/**
//	 * @param n the number of dimensions of the array
//	 * @param obj the generic array of etch.examples.ccmuser.CcmUser.UserConfiguration
//	 * @return the generic array of etch.examples.ccmuser.CcmUser.UserConfiguration converted to a native array of etch.examples.ccmuser.CcmUser.UserConfiguration
//	 */
//	public final static Object to_UserConfiguration( Class<?> c, Object obj )
//	{
//		return arrayValue2Native( obj, c );
//	}
//
//	/**
//	 * @param n the number of dimensions of the array
//	 * @param obj the generic array of etch.examples.ccmuser.CcmUser.Device
//	 * @return the generic array of etch.examples.ccmuser.CcmUser.Device converted to a native array of etch.examples.ccmuser.CcmUser.Device
//	 */
//	public final static Object to_Device( Class<?> c, Object obj )
//	{
//		return arrayValue2Native( obj, c );
//	}
//
//	/**
//	 * @param n the number of dimensions of the array
//	 * @param obj the generic array of etch.examples.ccmuser.CcmUser.Speeddial
//	 * @return the generic array of etch.examples.ccmuser.CcmUser.Speeddial converted to a native array of etch.examples.ccmuser.CcmUser.Speeddial
//	 */
//	public final static Object to_Speeddial( Class<?> c, Object obj )
//	{
//		return arrayValue2Native( obj, c );
//	}
}
