// Generated by:
// @EtchVersion@ (@EtchBuildTag@) / java @EtchVersion@ (@EtchBuildTag@)
// Fri Apr 11 09:58:16 CDT 2008

package etch.examples.cuae;


/**
 * Your custom implementation of BaseCuaeClient. Add methods here to provide
 * implementations of messages from the server.
 */
public class ImplCuaeClient extends BaseCuaeClient
{
	/**
	 * Constructs the ImplCuaeClient.
	 *
	 * @param server a connection to the server session. Use this to send a
	 * message to the server.
	 */
	public ImplCuaeClient( RemoteCuaeServer server )
	{
		this.server = server;
	}
	
	private final RemoteCuaeServer server;

	public Response doit2( Request req )
	{
		switch (req.code)
		{
			case 7: return new Response( "apple" );
			case 11: return new RespWithCode( "banana", 37 );
			case 99: return new Response( "prune" );
			default: return new RespWithCode( "me putz "+req.code+" in teh bukkit", 101 );
		}
	}
}