// Generated by:
// @EtchVersion@ (@EtchBuildTag@) / java @EtchVersion@ (@EtchBuildTag@)
// Fri Apr 11 09:58:16 CDT 2008

package etch.examples.cuae;

import etch.examples.cuae.Cuae.ReqWithMessage;
import etch.examples.cuae.Cuae.Request;

/**
 * Main program for CuaeClient. This program makes a connection to the
 * listener created by MainCuaeListener.
 */
public class MainCuaeClient implements CuaeHelper.CuaeClientFactory
{
	/**
	 * Main program for CuaeClient.
	 * 
	 * @param args
	 * @throws Exception
	 */
	public static void main( String[] args ) throws Exception
	{
		String uri = "tcp://localhost:4006";
		if (args.length > 0)
			uri = args[0];

		MainCuaeClient implFactory = new MainCuaeClient();
		
		RemoteCuaeServer server = CuaeHelper.newServer( uri, null,
			implFactory );

		server._startAndWaitUp( 4000 );

		System.out.println( "--- doit1( 23 ) -------------------------------------------" );
		System.out.printf( "doit1( 23 ) => %s\n",
			server.doit1( new Request( 23 ) ) );

		System.out.println( "--- doit1( 23, \"skiddoo\" ) -------------------------------------------" );
		System.out.printf( "doit1( 23, \"skiddoo\" ) => %s\n",
			server.doit1( new ReqWithMessage( 23, "skiddoo" ) ) );

		System.out.println( "--- doit1( 19 ) -------------------------------------------" );
		System.out.printf( "doit1( 19 ) => %s\n",
			server.doit1( new Request( 19 ) ) );

		System.out.println( "--- doit1( 13, \"unlucky friday\" ) -------------------------------------------" );
		System.out.printf( "doit1( 13, \"unlucky friday\" ) => %s\n",
			server.doit1( new ReqWithMessage( 13, "unlucky friday" ) ) );
		
		System.out.println( "--- doit( [23] ) -------------------------------------------" );
		System.out.printf( "doit3( [23] ) => [%s]\n",
			server.doit3( new Request[] { new Request( 23 ) } )[0] );

		Thread.sleep( 60*1000 );
		
		server._stopAndWaitDown( 4000 );
	}

	public CuaeClient newCuaeClient( RemoteCuaeServer server )
		throws Exception
	{
		return new ImplCuaeClient( server );
	}
}
