/* $Id$
 *
 * Copyright 2009-2010 Cisco Systems Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.02 at 02:28:29 PM CST 
//


package cisco.uc.cuae.etchrouter.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cisco.cuae.etchrouter.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cisco.cuae.etchrouter.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Module.Service.Consts }
     * 
     */
    public Module.Service.Consts createModuleServiceConsts() {
        return new Module.Service.Consts();
    }

    /**
     * Create an instance of {@link Module.Service.Exceptions }
     * 
     */
    public Module.Service.Exceptions createModuleServiceExceptions() {
        return new Module.Service.Exceptions();
    }

    /**
     * Create an instance of {@link Module.Service.Structs }
     * 
     */
    public Module.Service.Structs createModuleServiceStructs() {
        return new Module.Service.Structs();
    }

    /**
     * Create an instance of {@link Module.Service.Enums }
     * 
     */
    public Module.Service.Enums createModuleServiceEnums() {
        return new Module.Service.Enums();
    }

    /**
     * Create an instance of {@link Module.Service.Enums.Enum }
     * 
     */
    public Module.Service.Enums.Enum createModuleServiceEnumsEnum() {
        return new Module.Service.Enums.Enum();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link Module.Service }
     * 
     */
    public Module.Service createModuleService() {
        return new Module.Service();
    }

    /**
     * Create an instance of {@link Module.Service.Methods.Method }
     * 
     */
    public Module.Service.Methods.Method createModuleServiceMethodsMethod() {
        return new Module.Service.Methods.Method();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link Module }
     * 
     */
    public Module createModule() {
        return new Module();
    }

    /**
     * Create an instance of {@link Module.Service.Enums.Enum.Entry }
     * 
     */
    public Module.Service.Enums.Enum.Entry createModuleServiceEnumsEnumEntry() {
        return new Module.Service.Enums.Enum.Entry();
    }

    /**
     * Create an instance of {@link Module.Service.Externs.Extern }
     * 
     */
    public Module.Service.Externs.Extern createModuleServiceExternsExtern() {
        return new Module.Service.Externs.Extern();
    }

    /**
     * Create an instance of {@link Module.Service.Methods.Method.Authorize }
     * 
     */
    public Module.Service.Methods.Method.Authorize createModuleServiceMethodsMethodAuthorize() {
        return new Module.Service.Methods.Method.Authorize();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Module.Service.Externs.Extern.Externmap }
     * 
     */
    public Module.Service.Externs.Extern.Externmap createModuleServiceExternsExternExternmap() {
        return new Module.Service.Externs.Extern.Externmap();
    }

    /**
     * Create an instance of {@link Module.Service.Externs }
     * 
     */
    public Module.Service.Externs createModuleServiceExterns() {
        return new Module.Service.Externs();
    }

    /**
     * Create an instance of {@link Module.Service.Methods.Method.Result }
     * 
     */
    public Module.Service.Methods.Method.Result createModuleServiceMethodsMethodResult() {
        return new Module.Service.Methods.Method.Result();
    }

    /**
     * Create an instance of {@link Module.Service.Structs.Struct }
     * 
     */
    public Module.Service.Structs.Struct createModuleServiceStructsStruct() {
        return new Module.Service.Structs.Struct();
    }

    /**
     * Create an instance of {@link Module.Service.Methods }
     * 
     */
    public Module.Service.Methods createModuleServiceMethods() {
        return new Module.Service.Methods();
    }

    /**
     * Create an instance of {@link Module.Service.Consts.Const }
     * 
     */
    public Module.Service.Consts.Const createModuleServiceConstsConst() {
        return new Module.Service.Consts.Const();
    }

}
