## 
## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements. See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership. The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License. You may obtain a copy of the License at
## 
##   http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied. See the License for the
## specific language governing permissions and limitations
## under the License.
## 
GOFILES=\
	Mailbox.go\
	Flexbuffer.go\
	Util.go\
	Logger.go\
	StructValue.go\
	Type.go\
	Message.go\
	ValueFactory.go\
	Field.go\
	Validator.go\
	ImportExportHelper.go\
	Direction.go\
	IdName.go\
	IdNameMap.go\
	TypeMap.go\
	DefaultValueFactory.go\
	TaggedDataInput.go\
	TaggedDataOutput.go\
	BinaryTaggedData.go\
	BinaryTaggedDataInput.go\
	BinaryTaggedDataOutput.go\
	PlainMailBox.go\
	DeliveryService.go\
	DefaultDeliveryService.go\
	Packetizer.go\
	Messagizer.go\
	TcpConnection.go\
	TcpListener.go\
	SessionTransport.go\
	PlainMailBoxManager.go\
	EtchStub.go\

all:    
	8g  -o etch.8 ${GOFILES}
