## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements. See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership. The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License. You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied. See the License for the
## specific language governing permissions and limitations
## under the License.
#set($i = $intf.name())
FILES= \
	Base${i}Client.go\
	Base${i}Server.go\
	${i}Client.go\
	${i}.go\
	${i}Helper.go\
	${i}Server.go\
	Impl${i}Client.go\
	Impl${i}Server.go\
	Remote${i}Client.go\
	Remote${i}.go\
	Remote${i}Server.go\
	Stub${i}Client.go\
	Stub${i}.go\
	Stub${i}Server.go\
	ValueFactory${i}.go\

all: server
	8g -o ${i}client.8 -I ${ETCHLIBPATH} -I . Main${i}Client.go
	8l -L ${ETCHLIBPATH} -L . -o ${i}Client ${i}client.8

server: 
ifndef ETCHLIBPATH
	@echo Please call \"make ETCHLIBPATH=/some/path\",where /some/path contains etch.8
	false
endif
	8g -o ${helper.getPackageName($intf)}.8 -I ${ETCHLIBPATH} -I . ${FILES}
	8g -o ${i}server.8 -I ${ETCHLIBPATH} -I . Main${i}Listener.go
	8l -L ${ETCHLIBPATH} -L . -o ${i}Server ${i}server.8
