// This file automatically generated by:
//   Apache Etch 1.1.0-incubating (LOCAL-0) / java 1.1.0-incubating (LOCAL-0)
//   Thu Feb 19 12:21:28 CST 2009
// This file is automatically created for your convenience and will not be
// overwritten once it exists! Please edit this file as necessary to implement
// your service logic.

package org.apache.etch.examples.example;

import java.util.Date;

/**
 * Your custom implementation of BaseExampleFooServer. Add methods here to provide
 * implementations of messages from the client.
 */
public class ImplExampleFooServer extends BaseExampleFooServer
{
	/**
	 * Constructs the ImplExampleFooServer.
	 *
	 * @param client a connection to the client session. Use this to send a
	 * message to the client.
	 */
	public ImplExampleFooServer( RemoteExampleFooClient client )
	{
		this.client = client;
	}
	
	/**
	 * A connection to the client session. Use this to send a
	 * message to the client.
	 */
	@SuppressWarnings( "unused" )
	private final RemoteExampleFooClient client;

	@Override
	public Integer helloServer( String msg, Date d )
	{
		return msg.hashCode();
	}
	
	@Override
	public Integer foo( String msg )
	{
		return msg.hashCode();
	}
}