// This file automatically generated by:
//   Apache Etch 1.1.0-incubating (LOCAL-0) / java 1.1.0-incubating (LOCAL-0)
//   Thu Feb 19 12:21:28 CST 2009
// This file is automatically created for your convenience and will not be
// overwritten once it exists! Please edit this file as necessary to implement
// your service logic.

package org.apache.etch.examples.example;

/**
 * Your custom implementation of BaseExampleFooClient. Add methods here to provide
 * implementations of messages from the server.
 */
public class ImplExampleFooClient extends BaseExampleFooClient
{
	/**
	 * Constructs the ImplExampleFooClient.
	 *
	 * @param server a connection to the server session. Use this to send a
	 * message to the server.
	 */
	public ImplExampleFooClient( RemoteExampleFooServer server )
	{
		this.server = server;
	}
	
	/**
	 * A connection to the server session. Use this to send a
	 * message to the server.
	 */
	@SuppressWarnings( "unused" )
	private final RemoteExampleFooServer server;

	// TODO insert methods here to provide implementations of ExampleFooClient
	// messages from the server.
	
	@Override
	public void _sessionNotify( Object event ) throws Exception
	{
		if (event instanceof Throwable)
			((Throwable) event).printStackTrace();
		else
			System.out.println( "event = "+event );
	}
}