// This file automatically generated by:
//   @EtchVersion@ (@EtchBuildTag@) / csharp @EtchVersion@ (@EtchBuildTag@)
//   Tue Apr 15 15:02:10 CDT 2008


using System;

/**
 * Call to message translator for AsyncServer.
 */
namespace etch.bindings.csharp.examples.async
{

	public class ImplAsyncServer : BaseAsyncServer
	{

		/// 
		/// <summary>Constructs the ImplAsyncServer.</summary>
		///
 		/// <param name=client></param>
 		///
		public ImplAsyncServer(RemoteAsyncClient client )
		{
		    this.client = client;
            _delegate_async_free = my_async_free;
            _delegate_async_queued = my_async_queued;
            _delegate_sync = my_sync;      
		}

	    private readonly RemoteAsyncClient client;


        ///
        /// <summary>Begins the call to sync.</summary>
        ///
        public int? my_sync(
                int? count
            )
        {
            return count > 0 ? client.sync(count - 1) + 1 : 0;
        }
        ///
        /// <summary>Begins the call to async_queued.</summary>
        ///
        public int? my_async_queued(
                int? count
            )
        {
            return count > 0 ? client.async_queued(count - 1) + 1 : 0;
        }
        ///
        /// <summary>Begins the call to async_free.</summary>
        ///
        public int? my_async_free(
                int? count
            )
        {
            return count > 0 ? client.async_free(count - 1) + 1 : 0;
        }

		
		
	}
}