// This file automatically generated by:
//   @EtchVersion@ (@EtchBuildTag@) / csharp @EtchVersion@ (@EtchBuildTag@)
//   Mon Apr 28 11:23:44 CDT 2008
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Runtime.CompilerServices;
using Etch.Util;
using Etch.Msg;
using Etch.Support;
using Etch.Transport;

namespace etch.bindings.csharp.examples.types
{

///
///<summary> Main implementation for TypesListener. </summary>
///
public class MainTypesListener : TypesHelper.TypesServerFactory
{
	///
 	/// <summary>Main for TypesListener.</summary>
	/// <param name="args"></param>
	///
	public static void Main1(String[] args)
	{
		string uri = "tcp://localhost:4001";
		

		MainTypesListener implFactory = new MainTypesListener();
		Transport<SessionListener> listener = TypesHelper.NewListener( uri, null, implFactory );

		listener.TransportControl( TransportConsts.START_AND_WAIT_UP, 4000 );
	}

	///
	/// <summary>Constructs the MainTypesListener.</summary>
	///
	public MainTypesListener()
	{
		// Nothing to do.
	}

	///
	/// <summary>Return a new instance of TypesServer.</summary>
	/// @param client
	///
	public TypesServer NewTypesServer( RemoteTypesClient client )
	{
		return new ImplTypesServer( client );
	}
}

}