
// This file automatically generated by:
//   Apache Etch 1.2.0-incubating (LOCAL-0) / c 1.2.0-incubating (LOCAL-0)
//   Mon Mar 28 14:18:57 CEST 2011
// This file is automatically created and should not be edited!

/*
 * example_client_main.h
 * client exe main() private header
 */

#ifndef EXAMPLE_CLIENT_MAIN_H
#define EXAMPLE_CLIENT_MAIN_H

#include "etch_runtime.h"
#include "example_helper.h"
#include "example_client_impl.h"
#include "example_remote_server.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * example_listener_start(pplistener, uri, waitupms)
 * Start the listener at the given uri, waiting waitupms microseconds for listener startup.
 * The created listener is saved at address pointed to by pplistener.
 */
extern etch_status_t example_listener_start(i_sessionlistener** pplistener, wchar_t* uri, int waitupms);

/*
 * example_listener_stop(plistener, waitupms)
 * Stop the listener given by plistener, waiting waitupms microseconds to stop.
 */
extern etch_status_t example_listener_stop(i_sessionlistener* plistener, int waitupms);

#ifdef __cplusplus
} //extern "C"
#endif

#endif /* EXAMPLE_CLIENT_MAIN.H */
