// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / c 1.3.0-incubating (LOCAL-0)
//   Fri Jul 27 11:35:36 CEST 2012
// This file is automatically created for your convenience and will not be
// overwritten once it exists! Please edit this file as necessary to implement
// your service logic.

#include "ImplHelloWorldClient.h"

using namespace org_apache_etch_examples_helloworld_HelloWorld;

/**
 * Your custom implementation of BaseHelloWorldClient. Add methods here to provide
 * implementations of messages from the mServer.
 */

  ImplHelloWorldClient::ImplHelloWorldClient( RemoteHelloWorldServer* mServer )
  {
    this->mServer = mServer;
  }

  // TODO insert methods here to provide implementations of HelloWorldClient
  // messages from the mServer.
