// This file automatically generated by:
//   @EtchVersion@ (@EtchBuildTag@) / csharp @EtchVersion@ (@EtchBuildTag@)
//   Tue Apr 15 15:02:11 CDT 2008
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using Etch.Util;
using Etch.Msg;
using Etch.Support;
using Etch.Transport;
using etch.bindings.csharp.examples.cuae.types.Cuae;

namespace etch.bindings.csharp.examples.cuae
{

///
///<summary> Main implementation for CuaeClient. </summary>
///
public class MainCuaeClient : CuaeHelper.CuaeClientFactory
{
	///
	/// <summary>Main for CuaeClient</summary>
	/// <param name="args"></param>
	///
	public static void Main(String[] args)
	{
		string uri = "tcp://localhost:4001";
		if (args.Length > 0)
			uri = args[0];

        MainCuaeListener.Main1(new String[] { });


		MainCuaeClient implFactory = new MainCuaeClient();
		RemoteCuaeServer server = CuaeHelper.NewServer( uri, null, implFactory );
		
		server._TransportControl(Etch.Transport.TransportConsts.START_AND_WAIT_UP, 4000 );

        Console.WriteLine("--------doit(23)-------------------------------------");
        Console.WriteLine("doit( 23 ) => {0}\n",
            server.doit(new Request(23)));

        Console.WriteLine("--------doit(23,\"skiddoo\")-------------------------------------");
        Console.WriteLine("doit( 23,\"skiddoo\" ) => {0}\n",
            server.doit(new ReqWithMessage(23, "skiddoo")));



        Console.WriteLine("------------doit( 19 )-----------------------------");
        Console.WriteLine("doit( 19 ) => {0}\n",
            server.doit(new Request(19)));

        Console.WriteLine("------------doit( 13 )-----------------------------");
        Console.WriteLine("doit( 13,\"unlucky friday\" ) => {0}\n",
            server.doit(new ReqWithMessage(13, "unlucky friday")));

        Console.WriteLine("----------------------------------------------");
        Console.WriteLine("doit( 13 ) => {0}\n",
            server.doit(new Request(13)));

        Console.WriteLine("--- doit( 23 ) -------------------------------------------");
        Console.WriteLine("doit( [23] ) => {0}\n",
            server.doit3(new Request[] { new Request(23) })[0]);


		server._TransportControl(Etch.Transport.TransportConsts.STOP_AND_WAIT_DOWN, 4000 );

	}

	///
	/// <summary>Constructs the MainCuaeClient.</summary>
	///
	public MainCuaeClient()
	{
		// Nothing to do.
	}

	///
	/// <summary>Return a new instance of CuaeClient.</summary>
	/// @param server
	///
	public CuaeClient NewCuaeClient( RemoteCuaeServer server )
	{
		return new ImplCuaeClient( server );
	}

}

}