// Generated by:
// @EtchVersion@ (@EtchBuildTag@) / java @EtchVersion@ (@EtchBuildTag@)
// Thu Apr 10 15:02:07 CDT 2008

package etch.examples.chat;


/**
 * Main program for ChatClient. This program makes a connection to the
 * listener created by MainChatListener.
 */
public class MainChatClient implements ChatHelper.ChatClientFactory
{
	/**
	 * Main program for ChatClient.
	 * 
	 * @param args
	 * @throws Exception
	 */
	public static void main( String[] args ) throws Exception
	{
		String uri = "tcp://localhost:4005";
		if (args.length > 0)
			uri = args[0];

		MainChatClient implFactory = new MainChatClient();
		
		RemoteChatServer server = ChatHelper.newServer( uri, null,
			implFactory );

		server._startAndWaitUp( 4000 );

		// -------------------------------------------------------------
		// Insert Your Code Here
		// -------------------------------------------------------------

		server._stopAndWaitDown( 4000 );
	}

	public ChatClient newChatClient( RemoteChatServer server )
		throws Exception
	{
		return new ImplChatClient( server, null, false );
	}
}
