/*
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */


// This file automatically generated by:
//   Apache Etch 1.1.0-incubating (LOCAL-0) / c 1.1.0-incubating (LOCAL-0)
//   Fri Aug 28 15:58:20 CEST 2009
// This file is automatically created and should not be edited!

/*
 * helloworld_client.h
 * helloworld client interface.
 * combines java bindings's helloworldServer and BasehelloworldServer
 */

#ifndef HELLOWORLD_CLIENT_H
#define HELLOWORLD_CLIENT_H

#include "helloworld_interface.h"
#include "etch_sessionint.h"

#ifdef __cplusplus
extern "C" {
#endif

extern unsigned short CLASSID_HELLOWORLD_CLIENT_BASE;

//typedef struct helloworld_client_impl helloworld_client_impl;

/**
 * i_helloworld_client
 * helloworld client base interface
 */
typedef struct i_helloworld_client
{
    etch_object object;

	struct helloworld_client_impl* thisx;
    i_helloworld*  ihelloworld;
    
    

    /* - - - - - - - - - - -
     * objsession
     * - - - - - - - - - - -
     */
    i_objsession* iobjsession;
    etch_session_control _session_control;
    etch_session_notify  _session_notify;
    etch_session_query   _session_query;

    /* - - - - - - - - - - -
     * service virtuals
     * - - - - - - - - - - -
     */
    helloworld_say_hello say_hello;

    /* no client-directed items defined */

    /* - - - - - - - - - - -
    * service data
    * - - - - - - - - - - -
    */
    helloworld_user* user;

     /* - - - - - - - - - - -
     * private instance data
     * - - - - - - - - - - -
     */
    int server_id;

} i_helloworld_client;

//i_helloworld_client* new_helloworld_client_base(helloworld_client_impl* implobj);
i_helloworld_client* new_helloworld_client_base();


#ifdef __cplusplus
} //extern "C"
#endif

#endif /* HELLOWORLD_CLIENT_H */
