// This file automatically generated by:
//   Apache Etch 1.1.0-incubating (LOCAL-0) / java 1.1.0-incubating (LOCAL-0)
//   Wed Sep 15 17:22:46 CEST 2010
// This file is automatically created for your convenience and will not be
// overwritten once it exists! Please edit this file as necessary to implement
// your service logic.

package org.apache.etch.examples.helloworld;
/*
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */


import org.apache.etch.examples.helloworld.HelloWorld.user;

/**
 * Main program for HelloWorldClient. This program makes a connection to the
 * listener created by MainHelloWorldListener.
 */
public class MainHelloWorldClient implements HelloWorldHelper.HelloWorldClientFactory
{
	/**
	 * Main program for HelloWorldClient.
	 * 
	 * @param args command line arguments.
	 * @throws Exception
	 */
	public static void main( String[] args ) throws Exception
	{
		// TODO Change to correct URI
		//String uri = "udp://127.0.0.1:4001";
		String uri = "tcp://127.0.0.1:4001";
		
		RemoteHelloWorldServer server = HelloWorldHelper.newServer( uri, null,
			new MainHelloWorldClient() );

		// Connect to the service
		server._startAndWaitUp( 4000 );

		user u = new user(5, "User");
		System.out.println(server.say_hello(u));

		// Disconnect from the service
		server._stopAndWaitDown( 4000 );
	}

	public HelloWorldClient newHelloWorldClient( RemoteHelloWorldServer server )
		throws Exception
	{
		return new ImplHelloWorldClient( server );
	}
}
