// This file automatically generated by:
//   Apache Etch 1.1.0-incubating (LOCAL-0) / java 1.1.0-incubating (LOCAL-0)
//   Fri Jul 16 12:01:27 CEST 2010
// This file is automatically created and should not be edited!
// Re-implement these methods by overriding them in ImplhelloworldServer.

package etch.cbinding.test;
/*
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */


import org.apache.etch.bindings.java.support.ObjSession;


/**
 * Base implementation of helloworldServer, with default method implementations
 * which throw UnsupportedOperationException. Extend this class to provide
 * implementations of messages from the client.
 *
 * @see ImplhelloworldServer
 */
public class BasehelloworldServer implements helloworldServer, ObjSession
{
	public Object _sessionQuery( Object query ) throws Exception
	{
		throw new UnsupportedOperationException( "unknown query: "+query );
	}

	public void _sessionControl( Object control, Object value ) throws Exception
	{
		throw new UnsupportedOperationException( "unknown control: "+control );
	}

	public void _sessionNotify( Object event ) throws Exception
	{
		if (event instanceof Throwable)
			((Throwable) event).printStackTrace();
	}

	public String say_hello
	(
		etch.cbinding.test.helloworld.user to_whom
	)
	throws
		etch.cbinding.test.helloworld.UserUnknownException
	{
		throw new UnsupportedOperationException( "say_hello" );
	}
}
