// This file automatically generated by:
//   Apache Etch 1.1.0-incubating (LOCAL-0) / java 1.1.0-incubating (LOCAL-0)
//   Fri Jul 16 12:01:27 CEST 2010
// This file is automatically created and should not be edited!

package etch.cbinding.test;
/*
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */


import java.io.Serializable;


@SuppressWarnings("unused")
public interface helloworld
{
	@SuppressWarnings("serial")
	public class user
		implements Serializable
	{
		/**
		 * Constructs the user. Don't init any fields.
		 */
		public user()
		{
			// don't init any fields.
		}

		/**
		 * Constructs the user.
		 */
		public user
		(
			Integer id
			, String name
		)
		{
			this.id = id;
			this.name = name;
		}

		@Override
		public String toString()
		{
			return String.format( "user(id=%s; name=%s)", id, name );
		}

		public Integer id;

		/**
		 * Gets the value.
		 *
		 *
		 * @return the value.
		 */
		public Integer getId()
		{
			return id;
		}

		/**
		 * Sets the value.
		 *
		 *
		 * @param value the value.
		 */
		public void setId( Integer value )
		{
			this.id = value;
		}

		public String name;

		/**
		 * Gets the value.
		 *
		 *
		 * @return the value.
		 */
		public String getName()
		{
			return name;
		}

		/**
		 * Sets the value.
		 *
		 *
		 * @param value the value.
		 */
		public void setName( String value )
		{
			this.name = value;
		}
	}

	@SuppressWarnings("serial")
	public class UserUnknownException
		extends Exception
	{
		/**
		 * Constructs the UserUnknownException. Don't init any fields.
		 */
		public UserUnknownException()
		{
			// don't init any fields.
		}

		/**
		 * Constructs the UserUnknownException.
		 */
		public UserUnknownException
		(
			String mes
		)
		{
			this.mes = mes;
		}

		@Override
		public String getMessage()
		{
			return String.format( "mes=%s", mes );
		}

		public String mes;

		/**
		 * Gets the value.
		 *
		 *
		 * @return the value.
		 */
		public String getMes()
		{
			return mes;
		}

		/**
		 * Sets the value.
		 *
		 *
		 * @param value the value.
		 */
		public void setMes( String value )
		{
			this.mes = value;
		}
	}

}
