// This file automatically generated by:
//   Etch Version 0.95/csharp backend 0.95
//   Thu Aug 16 12:08:25 CDT 2007

namespace cisco.etch.examples
{

using System;
using Etch.Msg;
using Etch.Support;
using Etch.Transport;


///
/// <summary>Call to message translator for TwoWayServer.</summary>
///
public class RemoteTwoWayServer : RemoteTwoWay, TwoWayServer
{
	///
	/// <summary>Constructs the RemoteTwoWayServer.</summary>
	///
	/// <param name="svc"></param>
	///
	public RemoteTwoWayServer( DeliveryService svc ) : this( svc, new ValueFactoryTwoWay() )
	{
		
	}

	///
	/// <summary>Constructs the RemoteTwoWayServer.</summary>
	///
	/// <param name="svc"></param>
	/// <param name="vf"></param>
	///
	protected RemoteTwoWayServer( DeliveryService svc, ValueFactoryTwoWay vf ) : base( svc, vf )
	{
		
	}

	public void sendCUAEMessage(
		string msg
	)
	{
		_end_sendCUAEMessage( _begin_sendCUAEMessage(
			msg
		) );
	}
	
	public Mailbox<MailboxMessageSource> _begin_sendCUAEMessage(
		string msg
	)
	{
		Message _msg = _NewMessage( ValueFactoryTwoWay._mt_cisco_etch_examples_TwoWayServer_sendCUAEMessage );
		_msg.Add( ValueFactoryTwoWay._mf_msg, msg );
		return _svc.BeginCall( _msg );
	}
	
	public void _end_sendCUAEMessage( Mailbox<MailboxMessageSource> _mb )
	{
		try
		{
			
			_svc.EndVoidCall( _mb,
				ValueFactoryTwoWay._mt_cisco_etch_examples_TwoWayServer__result_sendCUAEMessage,
				ValueFactoryTwoWay._mf_result, 0 );
		}
		catch ( Exception _e )
		{
			throw new Exception( "unexpected", _e );
		}
	}

}

}