// This file automatically generated by:
//   Etch Version 0.95/csharp backend 0.95
//   Thu Aug 16 12:08:25 CDT 2007

namespace cisco.etch.examples
{

using System;
using Etch.Msg;
using Etch.Support;
using Etch.Transport;


///
/// <summary>Call to message translator for TwoWayClient.</summary>
///
public class RemoteTwoWayClient : RemoteTwoWay, TwoWayClient
{
	///
	/// <summary>Constructs the RemoteTwoWayClient.</summary>
	///
	/// <param name="svc"></param>
	///
	public RemoteTwoWayClient( DeliveryService svc ) : this( svc, new ValueFactoryTwoWay() )
	{
		
	}

	///
	/// <summary>Constructs the RemoteTwoWayClient.</summary>
	///
	/// <param name="svc"></param>
	/// <param name="vf"></param>
	///
	protected RemoteTwoWayClient( DeliveryService svc, ValueFactoryTwoWay vf ) : base( svc, vf )
	{
		
	}

	public void sendServletMessage(
		cisco.etch.examples.ConstsTwoWay.Selection selection
	)
	{
		_end_sendServletMessage( _begin_sendServletMessage(
			selection
		) );
	}
	
	public Mailbox<MailboxMessageSource> _begin_sendServletMessage(
		cisco.etch.examples.ConstsTwoWay.Selection selection
	)
	{
		Message _msg = _NewMessage( ValueFactoryTwoWay._mt_cisco_etch_examples_TwoWayClient_sendServletMessage );
		_msg.Add( ValueFactoryTwoWay._mf_selection, selection );
		return _svc.BeginCall( _msg );
	}
	
	public void _end_sendServletMessage( Mailbox<MailboxMessageSource> _mb )
	{
		try
		{
			
			_svc.EndVoidCall( _mb,
				ValueFactoryTwoWay._mt_cisco_etch_examples_TwoWayServer__result_sendServletMessage,
				ValueFactoryTwoWay._mf_result, 0 );
		}
		catch ( Exception _e )
		{
			throw new Exception( "unexpected", _e );
		}
	}

	public void bogus(
	)
	{
		Message _msg = _NewMessage( ValueFactoryTwoWay._mt_cisco_etch_examples_TwoWayClient_bogus );
		try
		{
			_svc.Send( _msg );
		}
		catch ( Exception _e )
		{
			throw new Exception( "unexpected", _e );
		}
	}
}

}