// This file automatically generated by:
//   Etch Version 0.95/csharp backend 0.95
//   Thu Aug 16 12:08:25 CDT 2007

namespace cisco.etch.examples
{
using System;

///
///
public interface TwoWayClient : TwoWay
{
	///
	///
	void sendServletMessage(
		cisco.etch.examples.ConstsTwoWay.Selection selection
	)
;
	///
	/// Temporary work around an etch bug.
	///
	void bogus(
	)
;
}

public abstract class ConstsTwoWayClient
{
}
}