// This file automatically generated by:
//   Etch Version 0.95/csharp backend 0.95
//   Thu Aug 16 12:08:25 CDT 2007

namespace cisco.etch.examples
{
using System;

///
///
public interface TwoWayServer : TwoWay
{
	///
	///
	void sendCUAEMessage(
		string msg
	)
;
}

public abstract class ConstsTwoWayServer
{
}
}