// This file automatically generated by:
//   @EtchVersion@ (@EtchBuildTag@) / csharp @EtchVersion@ (@EtchBuildTag@)
//   Tue Apr 15 15:02:10 CDT 2008


using System;
using Etch.Support;

/**
 * Call to message translator for ClosingClient.
 */
namespace etch.bindings.csharp.examples.closing
{

	public class ImplClosingClient : BaseClosingClient, ObjSession
	{

		/// 
		/// <summary>Constructs the ImplClosingClient.</summary>
		///
 		/// <param name=server></param>
 		///
		public ImplClosingClient(RemoteClosingServer server )
		{
		    this.server = server;
		}

	    private readonly RemoteClosingServer server;

      

        public new void _SessionNotify(Object eventObj)
        {
            Console.WriteLine("ImplClosingClient._sessionNotify" + eventObj);
        }

		
	}
}