// This file automatically generated by:
//   Etch 1.0.0 (LOCAL-0) / java 1.0.0 (LOCAL-0)
//   Fri Jan 09 11:53:48 CST 2009
// This file is automatically created for your convenience and will not be
// overwritten once it exists! Please edit this file as necessary to implement
// your service logic.

package org.apache.etch.services.config;


/**
 * Your custom implementation of BaseConfigurationClient. Add methods here to provide
 * implementations of messages from the server.
 */
public class ImplConfigurationClient extends BaseConfigurationClient
{
	/**
	 * Constructs the ImplConfigurationClient.
	 *
	 * @param server a connection to the server session. Use this to send a
	 * message to the server.
	 */
	public ImplConfigurationClient( RemoteConfigurationServer server )
	{
		this.server = server;
	}
	
	/**
	 * A connection to the server session. Use this to send a
	 * message to the server.
	 */
	@SuppressWarnings( "unused" )
	private final RemoteConfigurationServer server;

	// TODO insert methods here to provide implementations of ConfigurationClient
	// messages from the server.
}