// This file automatically generated by:
//   @EtchVersion@ (@EtchBuildTag@) / csharp @EtchVersion@ (@EtchBuildTag@)
//   Wed Apr 30 16:35:57 CDT 2008

using Etch.Util;

using System;

using etch.bindings.csharp.examples.mixin.types.Foo;
using etch.bindings.csharp.examples.mixin.bar.types.Bar;

/**
 * Call to message translator for FooClient.
 */
namespace etch.bindings.csharp.examples.mixin
{

	public class ImplFooClient : BaseFooClient
	{

		/// 
		/// <summary>Constructs the ImplFooClient.</summary>
		///
 		/// <param name=server></param>
 		///
		public ImplFooClient(RemoteFooServer server )
		{
		    this.server = server;
		}

	    private readonly RemoteFooServer server;
	
		// Implement delegates or provide implementation of server
		
	}
}