// Generated by:
// @EtchVersion@ (@EtchBuildTag@) / java @EtchVersion@ (@EtchBuildTag@)
// Fri Apr 11 07:45:30 CDT 2008

package etch.bindings.java.compiler.test;

/**
 * Your custom implementation of BaseInheritanceServer. Add methods here to provide
 * implementations of messages from the client.
 */
public class ImplInheritanceServer extends BaseInheritanceServer
{
	/**
	 * Constructs the ImplInheritanceServer.
	 *
	 * @param client a connection to the client session. Use this to send a
	 * message to the client.
	 */
	public ImplInheritanceServer( RemoteInheritanceClient client )
	{
		this.client = client;
	}
	
	private final RemoteInheritanceClient client;

	public Object f1( Object v )
	{
		return v;
	}

	public S1 f2( S1 v )
	{
		return v;
	}

	public S2 f3( S2 v )
	{
		return v;
	}

	public S3 f4( S3 v )
	{
		return v;
	}

	public Object[] f5( Object[] v )
	{
		return v;
	}

	public S1[] f6( S1[] v )
	{
		return v;
	}

	public S2[] f7( S2[] v )
	{
		return v;
	}

	public S3[] f8( S3[] v )
	{
		return v;
	}
}