// This file automatically generated by:
//   @EtchVersion@ (@EtchBuildTag@) / java @EtchVersion@ (@EtchBuildTag@)
//   Tue Jan 22 14:34:05 GMT-06:00 2008

package etch.bindings.java.compiler.test;


/**
 * Call to message translator for TestIncludesServer.
 */
public class ImplTestIncludesServer implements TestIncludesServer
{
	/**
	 * Constructs the ImplTestIncludesServer.
	 *
 	 * @param client
 	 */
	public ImplTestIncludesServer(TestIncludesClient client) 
	{
		// TODO Auto-generated constructor stub
	}
 	 public Integer incr(
		Integer x
	)
	{
		throw new UnsupportedOperationException();
	}
 	 public Integer testConst2(
	)
	{
		throw new UnsupportedOperationException();
	}
 	 public Integer testConst3(
	)
	{
		throw new UnsupportedOperationException();
	}
 	 public Integer testEnum2(
	)
	{
		throw new UnsupportedOperationException();
	}
 	 public Integer doNothing(
	)
	{
		throw new UnsupportedOperationException();
	}
}
