 // This file automatically generated by
 //  @EtchVersion@ (@EtchBuildTag@) / java @EtchVersion@ (@EtchBuildTag@)
 //  Mon Nov 12 14:29:21 CST 2007
package etch.bindings.java.compiler.test;


import metreos.util.URL;
import etch.bindings.java.transport.Transport;
import etch.bindings.java.compiler.test.TestHelper.TestServerFactory;


/**
 * Main implementation for TestListener.
 */
public class MainTestListener implements TestServerFactory
{
	/**
 	 * Main for TestListener.
	 * @param args
	 * @throws Exception
	 */
	public static void main(String[] args)
		throws Exception
	{
		URL uri = new URL("tcp://0.0.0.0:4001");

		MainTestListener implFactory = new MainTestListener();
		Transport listener = TestHelper.newTestListener( uri, null, implFactory );

		listener.transportControl( Transport.START_AND_WAIT_UP, 4000 );
	}

	/**
	 * Constructs the MainTestListener.
	 */
	public MainTestListener()
	{
		// Nothing to do.
	}

	/**
	 * Return a new instance of TestServer.
	 * @param client
	 */
	public TestServer newTestServer( TestClient client )
	{
		return new ImplTestServer( client );
	}
}
