// This file automatically generated by:
//   @EtchVersion@ (@EtchBuildTag@) / java @EtchVersion@ (@EtchBuildTag@)
//   Mon Nov 12 14:29:21 CST 2007

package etch.bindings.java.compiler.test;

import etch.bindings.java.util.StrIntHashMap;

/**
 * Call to message translator for TestServer.
 */
@SuppressWarnings("unused")
public class RemoteTestServer extends RemoteTest implements TestServer
{
	/**
	 * Constructs the RemoteTestServer.
	 *
	 * @param svc
	 */
	public RemoteTestServer( etch.bindings.java.support.DeliveryService svc )
	{
		this( svc, new ValueFactoryTest() );
	}

	/**
	 * Constructs the RemoteTestServer.
	 *
	 * @param svc
	 * @param vf
	 */
	protected RemoteTestServer( etch.bindings.java.support.DeliveryService svc, ValueFactoryTest vf )
	{
		super( svc, vf );
	}

}
