// This file automatically generated by:
//   Etch Version 0.95/java backend 0.95
//   Thu Aug 16 11:48:00 CDT 2007

package cisco.etch.examples;


/**
 * Call to message translator for TwoWayClient.
 */
public class RemoteTwoWayClient extends RemoteTwoWay implements TwoWayClient
{
	/**
	 * Constructs the RemoteTwoWayClient.
	 *
	 * @param svc
	 */
	public RemoteTwoWayClient( etch.bindings.java.support.DeliveryService svc )
	{
		this( svc, new ValueFactoryTwoWay() );
	}

	/**
	 * Constructs the RemoteTwoWayClient.
	 *
	 * @param svc
	 * @param vf
	 */
	protected RemoteTwoWayClient( etch.bindings.java.support.DeliveryService svc, ValueFactoryTwoWay vf )
	{
		super( svc, vf );
	}

	public void sendServletMessage(
		cisco.etch.examples.TwoWay.Selection selection
	)
	{
		_end_sendServletMessage( _begin_sendServletMessage(
			selection
		) );
	}
	
	public etch.bindings.java.support.Mailbox<?> _begin_sendServletMessage(
		cisco.etch.examples.TwoWay.Selection selection
	)
	{
		etch.bindings.java.msg.Message _msg = _newMessage( ValueFactoryTwoWay._mt_cisco_etch_examples_TwoWayClient_sendServletMessage );
		_msg.put( ValueFactoryTwoWay._mf_selection, selection );
		return _svc.begincall( _msg );
	}
	
	public void _end_sendServletMessage( etch.bindings.java.support.Mailbox<?> _mb )
	{
		try
		{
			
			_svc.endvoidcall( _mb,
				ValueFactoryTwoWay._mt_cisco_etch_examples_TwoWayServer__result_sendServletMessage,
				ValueFactoryTwoWay._mf_result, 0 );
		}
		catch ( Exception _e )
		{
			if (_e instanceof RuntimeException) throw (RuntimeException) _e;
			throw new RuntimeException( "unexpected exception from peer", _e );
		}
	}

	public void bogus(
	)
	{
		etch.bindings.java.msg.Message _msg = _newMessage( ValueFactoryTwoWay._mt_cisco_etch_examples_TwoWayClient_bogus );
		try
		{
			_svc.send( _msg );
		}
		catch ( Exception _e )
		{
			if (_e instanceof RuntimeException) throw (RuntimeException) _e;
			throw new RuntimeException( "unexpected exception from peer", _e );
		}
	}
}
