// This file automatically generated by:
//   Etch Version 0.95/java backend 0.95
//   Thu Aug 16 11:48:00 CDT 2007

package cisco.etch.examples;

import etch.bindings.java.msg.Message;
import etch.bindings.java.support.MessageSource;
import etch.bindings.java.support.Pool;
import etch.bindings.java.support._Etch_AuthException;
import metreos.core.Who;
import etch.bindings.java.support.StubBase;
import etch.bindings.java.support.Pool.PoolRunnable;

/**
 * Message to call translator for TwoWay.
 */
public class StubTwoWay extends StubBase
{
	/**
	 * Stub for TwoWay.
	 * @param obj the implementation of TwoWay responsive to requests.
	 * @param pool thread pool used to run AsyncReceiverMode.FREE methods.
	 * @param free thread pool used to run AsyncReceiverMode.FREE methods.
	 */
	public StubTwoWay( TwoWay obj, Pool pool, Pool free )
	{
		super( obj, pool, free );
		this._obj = obj;
	}
	
	@SuppressWarnings("unused")
	private final TwoWay _obj;

	@Override
	public boolean message( final MessageSource _src, final Who _sender, final Message _msg )
		throws Exception
	{
		if (_msg == null)
		{
			super.message( _src, _sender, _msg );
			return true;
		}

		switch (_msg.type().getId())
		{
			default:
				return super.message( _src, _sender, _msg );
		}
	}
}
