// This file automatically generated by:
//   Apache Etch 1.2.0-incubating (LOCAL-0) / csharp 1.2.0-incubating (LOCAL-0)
//   Mon Mar 28 12:14:36 CEST 2011
// This file is automatically created for your convenience and will not be
// overwritten once it exists! Please edit this file as necessary to implement
// your service logic.

using System;


using org.apache.etch.examples.mixin.types.ExampleMixin;

using org.apache.etch.examples.mixin.types.Example;

///<summary>Your custom implementation of BaseExampleClient. Add methods here to provide
///implementation of messages from the server. </summary>
namespace org.apache.etch.examples.mixin
{
	///<summary>Implementation for ImplExampleClient</summary>
	public class ImplExampleClient : BaseExampleClient
	{
		/// <summary>Constructs the ImplExampleClient.</summary>
 		/// <param name="server">a connection to the server session. Use this to
 		/// send a message to the server.</param>
		public ImplExampleClient(RemoteExampleServer server)
		{
			this.server = server;
		}
		
		/// <summary>A connection to the server session. Use this to
 		/// send a message to the server.</summary>
		private readonly RemoteExampleServer server;
	
		// TODO: Implement delegates or provide implementation of ExampleClient
		// messages from the server
	}
}