// Generated by:
// @EtchVersion@ (@EtchBuildTag@) / java @EtchVersion@ (@EtchBuildTag@)
// Mon Apr 14 20:10:55 CDT 2008

package etch.examples.types;


/**
 * Your custom implementation of BaseTypesClient. Add methods here to provide
 * implementations of messages from the server.
 */
public class ImplTypesClient extends BaseTypesClient
{
	/**
	 * Constructs the ImplTypesClient.
	 *
	 * @param server a connection to the server session. Use this to send a
	 * message to the server.
	 */
	public ImplTypesClient( RemoteTypesServer server )
	{
		this.server = server;
	}
	
	private final RemoteTypesServer server;

	// TODO insert methods here to provide implementations of TypesClient
	// messages from the server.
}