// Generated by:
// @EtchVersion@ (@EtchBuildTag@) / java @EtchVersion@ (@EtchBuildTag@)
// Mon Apr 14 20:10:55 CDT 2008

package etch.examples.types;

import etch.util.core.io.Transport;

/**
 * Main program for TypesServer. This program makes a listener to accept
 * connections from MainTypesClient.
 */
public class MainTypesListener implements TypesHelper.TypesServerFactory
{
	/**
	 * Main program for TypesServer.
	 * 
	 * @param args
	 * @throws Exception
	 */
	public static void main( String[] args ) throws Exception
	{
		String uri = "tcp://0.0.0.0:4001";
		
		Transport<?> listener = TypesHelper.newListener( uri, null,
			new MainTypesListener() );

		listener.transportControl( Transport.START_AND_WAIT_UP, 4000 );
	}

	public TypesServer newTypesServer( RemoteTypesClient client )
	{
		return new ImplTypesServer( client );
	}
}
